default: &default
  adapter: postgresql #どのデータベースをDBMS使用するか設定
  encoding: unicode #どの文字コードを使うか設定 UTF-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: sample_development
test:
  <<: *default
  database: sample_test
production:
  <<: *default
  database: sample_production
  username: sample
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
